module.exports.list = (member) => [
	`**${member.user.tag}** just joined the server - glhf!`,
	`**${member.user.tag}** just joined. Everyone, look busy!`,
	`**${member.user.tag}** just joined. Can I get a heal?`,
	`**${member.user.tag}** joined your party.`,
	`**${member.user.tag}** joined. You must construct additional pylons.`,
	`Ermagherd. **${member.user.tag}** is here.`,
	`Welcome, **${member.user.tag}**. Stay awhile and listen.`,
	`Welcome, **${member.user.tag}**. We were expecting you ( ͡° ͜ʖ ͡°)`,
	`Welcome, **${member.user.tag}**. We hope you brought pizza.`,
	`Welcome **${member.user.tag}**. Leave your weapons by the door.`,
	`A wild **${member.user.tag}** appeared.`,
	`Swoooosh. **${member.user.tag}** just landed.`,
	`Brace yourselves. **${member.user.tag}** just joined the server.`,
	`**${member.user.tag}** just joined. Hide your bananas.`,
	`**${member.user.tag}** just arrived. Seems OP - please nerf.`,
	`**${member.user.tag}** just slid into the server.`,
	`A **${member.user.tag}** has spawned in the server.`,
	`Big **${member.user.tag}** showed up!`,
	`Where’s **${member.user.tag}**? In the server!`,
	`**${member.user.tag}** hopped into the server. Kangaroo!!`,
	`**${member.user.tag}** just showed up. Hold my beer.`,
	`Challenger approaching - **${member.user.tag}** has appeared!`,
	`It's a bird! It's a plane! Nevermind, it's just **${member.user.tag}**.`,
	`It's **${member.user.tag}**! Praise the sun! \\[T]/`,
	`Never gonna give **${member.user.tag}** up. Never gonna let **${member.user.tag}** down.`,
	`Ha! **${member.user.tag}** has joined! You activated my trap card!`,
	`Cheers, love! **${member.user.tag}**'s here!`,
	`Hey! Listen! **${member.user.tag}** has joined!`,
	`We've been expecting you **${member.user.tag}**`,
	`It's dangerous to go alone, take **${member.user.tag}**!`,
	`**${member.user.tag}** has joined the server! It's super effective!`,
	`Cheers, love! **${member.user.tag}** is here!`,
	`**${member.user.tag}** is here, as the prophecy foretold.`,
	`**${member.user.tag}** has arrived. Party's over.`,
	`Ready player **${member.user.tag}**`,
	`**${member.user.tag}** is here to kick butt and chew bubblegum. And **${member.user.tag}** is all out of gum.`,
	`Hello. Is it **${member.user.tag}** you're looking for?`,
	`**${member.user.tag}** has joined. Stay a while and listen!`,
	`Roses are red, violets are blue, **${member.user.tag}** joined this server with you`,
];

module.exports.leave = (member) => [
	`Hey! Listen! **${member.user.tag}** has left!`,
	`Where’s **${member.user.tag}**? Not in this server!`,
	`A **${member.user.tag}** has despawned in the server.`,
	`**${member.user.tag}** left the party.`,
	`A wild **${member.user.tag}** disappeared.`,
	`**${member.user.tag}** just left the server - glhf!`,
	`**${member.user.tag}** just left. Everyone, let's party!`,
	`**${member.user.tag}** has left the game.`,
	`**${member.user.tag}** pressed the wrong button, Goodbye.`,
	`**${member.user.tag}** so sad to see you leave!`,
	`Ermagherd. **${member.user.tag}** just left.`,
	`Goodbye **${member.user.tag}**, We will miss you!`,
	`Welcome **${member.user.tag}**! Oh Nevermind! He left. (╯°□°）╯︵ ┻━┻`,
];
